### ISSUE TITLE
requests.exceptions.ConnectionError: ('Connection aborted.', timeout('The write operation timed out',))

### ISSUE THREAD

**Issue by begyy** [ivknv/yadisk#12]
когда отправляешь больше 100мб такой ошибка входят

**Comment by ivknv** [comment]
Выглядит как уже известная проблема: #11

**Comment by begyy** [comment]
upload(file_path, f"/{upload_path}", **{'timeout': 250}) ??

**Comment by ivknv** [comment]
Что-нибудь в этом роде. Достаточно указать только увеличенный read timeout (например, `timeout=(15, 250)`).

**Comment by ivknv** [comment]
Конкретные необходимые значения таймаута могут зависеть от размера загружаемого файла, это нужно подобрать оптимальное значение.

**Comment by begyy** [comment]
спасибо
