### ISSUE TITLE
How to use behind the proxy

### ISSUE THREAD

**Issue by Andrewkha** [ivknv/yadisk#13]
Hi

I'm behind the proxy on my Windows system. I have used 'set http_proxy' and 'set https_proxy' to configure system proxies. And, for example, I can use requests lib with no issues:
`import requests
print(requests.get('http://google.com').text
`
However if I try using your lib when behind the proxy, I'm getting:

> requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='cloud-api.yandex.net', port=443): Max retries exceeded with url: /v1/disk (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000019DB5A5A7C0>, 'Connection to cloud-api.yandex.net timed out. (connect timeout=10.0)'))

How can I work around it?

**Comment by ivknv** [comment]
This seems like an issue with the proxy.
Have you tried doing something like sending requests specifically to `https://cloud-api.yandex.net` instead of google?
It just doesn't seem right because this library uses requests as well.

**Comment by Andrewkha** [comment]
You're right, sorry for bothering. Smth is wrong with https requests, while http is working well
