### ISSUE TITLE
Как получить ссылку на папку?

### ISSUE THREAD

**Issue by Cergey2202** [ivknv/yadisk#14]
Как получить ссылку на папку? метод ```get_download_link``` возвращает ссылку на скачивание zip архива, а мне нужна ссылка на скачивание папок, но с интерфейсом, например как эта: ```https://yadi.sk/d/FUTI4ODm9Pn9Dg``` Я пробовал использовать метод ```publish```, котрый исходя из документации дожен вернуть обьект LinkObject, в котором будет ссылка, я получил обьект, но есди я вставлю эту ссылку в браузер, то я получаю ответ:
```{"message": "Не авторизован.", "description": "Unauthorized", "error": "UnauthorizedError"}```
 как можно получить ссылку на папку, которой можно поделиться файлом?

**Comment by ivknv** [comment]
`publish()` возвращает ссылку на запрос REST API, для получения мета-информации об указанном ресурсе.

Публичную ссылку для папки можно получить с помощью метода `get_meta()` (свойство `public_url` объекта [`ResourceObject`](https://yadisk.readthedocs.io/ru/latest/docs.html#yadisk.objects.resources.ResourceObject)):
```python
y = yadisk.YaDisk(...)

print("Публичная ссылка: %s" % (y.get_meta("<Путь к папке>").public_url,))
```

**Comment by Cergey2202** [comment]
Спасибо, хорошего вам дня)
