### ISSUE TITLE
Как получить прямую ссылку на файл?

### ISSUE THREAD

**Issue by Cergey2202** [ivknv/yadisk#15]
Здравствуйте, меня интересует, возможно ли получить прямую ссылку на файл, то есть что бы ссылка заканчивалась на ```.mp4, .txt, .mp3...```?
Если да, то как?

**Comment by ivknv** [comment]
Прямую ссылку на скачивание ресурса можно получить только через методы `get_download_link()` / `get_public_download_link()`. Если вам нужно извлечь информацию о файле из ссылки, то можно разве что извлечь GET параметр filename из URL, но документация ничего не говорит об этом.
