### ISSUE TITLE
Скорость загрузки файла с ПК

### ISSUE THREAD

**Issue by Pacifist2503** [ivknv/yadisk#16]
Добрый день!

Скорость загрузки 14 мб .mp3 составляет около 2 минут
Тот же файл в браузере грузится за доли сек
Это особенности api или я что-то не учел?
Спасибо!

**Comment by 555Russich** [comment]
На данный момент проблема со скоростью загрузки файлов НА яндекс диск актуальна. Не знаю с какими конкретно расширениями, но видео `.avi` размером 500МБ у меня грузилось 48 минут :-1: :-1: :-1: 

Убрал расширение из названия и все ок, загрузилось как в браузере за 30 сек

**Comment by maxifly** [comment]
Я нашёл ссылку, где человек эксперимент с разными расширениями провёл
https://python.su/forum/topic/40819/
