### ISSUE TITLE
Progress bar

### ISSUE THREAD

**Issue by tikhonovpavel** [ivknv/yadisk#17]
Очень не хватает функционала полоски загрузки для больших файлов

**Comment by ivknv** [comment]
Библиотека по-большей части является простой оберткой над `requests`.
К сожалению `requests` не предоставляет прямого способа отслеживать прогресс загрузки файлов.
Если вам нужно отслеживать прогресс, вы можете создать file-like объект-обертку, переопределить метод `read()` и в нем косвенно отслеживать прогресс загрузки (еще по-идее можно использовать `tell()`).

Вот пример того, как можно загрузить файл, отображая прогресс бар (на основе этого [гиста](https://gist.github.com/tyhoff/b757e6af83c1fd2b7b83057adf02c139)):
```python
import os
from tqdm import tqdm
from tqdm.utils import CallbackIOWrapper
import yadisk

file_path = "test_file.zip"
file_size = os.stat(file_path).st_size
destination_path = "/test_file.zip"

y = yadisk.YaDisk(token="<ТОКЕН>")

with open(file_path, "rb") as f:
    with tqdm(total=file_size, unit="B", unit_scale=True, unit_divisor=1024) as t:
        wrapped_file = CallbackIOWrapper(t.update, f, "read")

        y.upload(wrapped_file, destination_path)
```
