### ISSUE TITLE
Работа с альбомами 

### ISSUE THREAD

**Issue by survtur** [ivknv/yadisk#18]
В документации к API Диска я не нашёл упоминания о работе с альбомами (группами фотографий). Может быть кто-то знает как работать с публичными альбомами по API?

Вот пример публичного альбома https://disk.yandex.ru/a/YVYGWGn3x4K6Tg

**Comment by ivknv** [comment]
Судя по всему, REST API не поддерживает работу с альбомами.

**Comment by and7ey** [comment]
Не появилось ли API для этого? Может, альбом в метаданных как-то задается?

**Comment by ivknv** [comment]
@and7ey В официальной документации к API Диска по прежнему ничего нет про альбомы.

**Comment by and7ey** [comment]
@ivknv это я, конечно же, тоже посмотрел. Возможно, кто-то разобрался как это работает и что-то придумал :)

**Comment by ayazzali** [comment]
Все еще нет никакого доступа к альбомам. Дико не хватает(
