### ISSUE TITLE
Одновременное использование приложения двумя процессами

### ISSUE THREAD

**Issue by PR0J3CT12** [ivknv/yadisk#19]
Правильно ли я понял, что Яндекс не дает использовать приложения двумя процессами одновременно? Вылетает ошибка ResourceIsLockedError, если запустить два процесса одновременно.
Или я что-то делаю не так?

**Comment by ivknv** [comment]
`ResourceIsLockedError` обычно возвращается, если вы пытаетесь совершить несколько операций с одним файлом/папкой одновременно (например, загрузка файла в папку, которая все еще удаляется). А так явного ограничения на количество параллельных запросов нету. Причина скорее всего в ваших конкретных запросах.
