### ISSUE TITLE
Ошибка Доступ запрещён. Возможно, у приложения недостаточно прав для данного действия. (Forbidden / ForbiddenError)

### ISSUE THREAD

**Issue by thug21** [ivknv/yadisk#34]
При создании приложения указал доступ к веб сервисам, но в консоли сейчас есть только доступ веб-сервисы и больше никаких настроек нет.

Пробую выполнить код собранный из примеров
```
y = yadisk.YaDisk("--", "--")
url = y.get_code_url()

print("Go to the following url: %s" % url)
code = input("Enter the confirmation code: ")

try:
    response = y.get_token(code)
except yadisk.exceptions.BadRequestError:
    print("Bad code")
    sys.exit(1)

y.token = response.access_token

if y.check_token():
    print("Sucessfully received token!")
else:
    print("Something went wrong. Not sure how though...")

print(y.check_token())


y.upload("C:\\...\\test.ini","/test.ini")

```
Вывод консоли
```
Go to the following url: https://oauth.yandex.ru/authorize?response_type=code&client_id=8276f155c47943e3813ee95275c9fab2&display=popup&force_confirm=yes
Enter the confirmation code: 4767659
Sucessfully received token!

```
На этапе загрузки получаю:
`
Получаю ошибку yadisk.exceptions.ForbiddenError: Доступ запрещён. Возможно, у приложения недостаточно прав для данного действия. (Forbidden / ForbiddenError)
`

Подскажите в чем может быть проблема?

**Comment by thug21** [comment]
отвечаю. Приложение надо создавать из расширенной формы (https://oauth.yandex.ru/client/new ) в ней можно выбрать  доступ к Яндекс.диску

**Comment by Zapzatron** [comment]
Есть ли информация, где сейчас нужно выдавать доступ к Яндекс.диску?
![image](https://github.com/user-attachments/assets/3f51f719-0db6-413b-9467-e421dce47403)

**Comment by Zapzatron** [comment]
Всё равно ошибка. Я что-то не добавил?
![image](https://github.com/user-attachments/assets/5f15510c-723a-4a6f-a6c5-3718442bcb30)
