### ISSUE TITLE
Downloading photos/videos from unlimited storage | Скачивание фото\видео из безлимитного хранилища

### ISSUE THREAD

**Issue by LordSkare** [ivknv/yadisk#36]
Hello.

Tell me, is it possible to download photos/videos from the unlimited storage into which Yandex allows downloading from mobile applications?

Are there any methods at all for retrieving these files via the Rest API?

------------------

Здравствуйте.

Подскажите, есть ли возможность скачивать фото\видео из безлимитного хранилища, в которое яндекс дает загружать с мобильных приложений? 

Есть ли вообще какие-то методы получения этих файлов через Rest API?

**Comment by ivknv** [comment]
I'm not familiar with the unlimited storage, but if it's not visible as a regular file/directory on Yandex.Disk and you cannot see it in the Files tab in the client, then you probably can't download it.

**Comment by LordSkare** [comment]
> I'm not familiar with the unlimited storage, but if it's not visible as a regular file/directory on Yandex.Disk and you cannot see it in the Files tab in the client, then you probably can't download it.

Yes, thank you, Yandex technical support confirmed that this is not possible now, but they will discuss adding this functionality to the API

**Comment by LordSkare** [comment]
Нашёл метод получения этих файлов, правда он пока ещё закрыт - я получаю 403 код 

https://cloud-api.yandex.net/v1/disk/photounlim/resources/last-modified
https://cloud-api.yandex.net/v1/disk/photounlim/resources/download

На самом деле довольно много неофициальных способов получения различных данных удалось обнаружить в ходе своих изысканий, в частности связанных с лентой, альбомами, историей изменений и другими, некоторые из них работают. Файлы которые я обнаружил датируются началом 2022 года. К сожалению, Яндекс не торопится обновлять своё API 


-----------

I found a method for obtaining these files, although it is still closed - I get a 403 code

https://cloud-api.yandex.net/v1/disk/photounlim/resources/last-modified
https://cloud-api.yandex.net/v1/disk/photounlim/resources/download

In fact, we were able to discover quite a few unofficial methods for obtaining various data during our research, in particular related to the feed, albums, change history and others, some of them work. The files I discovered date back to early 2022. Unfortunately, Yandex is in no hurry to update its API

**Comment by LordSkare** [comment]
Так, у меня получилось список файлов из photounlim , использую эндпоинт по получения фотосрезов (альбомы, автоматически созданные яндексом), но к сожалению, я не понимаю, как получить ссылки..
Есть у кого идеи? @ivknv ?

`import requests
import json

def get_photoslice_info(token, client_id, client_secret):
    url = "https://cloud-api.yandex.net/v1/disk/photoslice"
    headers = {
        "Authorization": f"OAuth {token}",
        "Client-ID": client_id,
        "Client-Secret": client_secret
    }

    response = requests.post(url, headers=headers)  # Используем метод POST

    if response.status_code == 200:
        return response.json()
    else:
        print(f"Ошибка {response.status_code}: {response.text}")
        return None

def get_photoslice_details_and_download_links(token, url):
    headers = {"Authorization": f"OAuth {token}"}
    response = requests.get(url, headers=headers)

    if response.status_code == 200:
        photoslice_details = response.json()
        download_links = []

        # Предполагаем, что в ответе есть список файлов, и каждый файл содержит URL для скачивания
        for file in photoslice_details.get("items", []):
            if "file" in file:
                download_url = file["file"].get("download_url")
                if download_url:
                    download_links.append(download_url)

        return photoslice_details, download_links
    else:
        print(f"Ошибка при получении деталей фотослайса {response.status_code}: {response.text}")
        return None, None

def save_to_json(data, filename):
    with open(filename, 'w', encoding='utf-8') as file:
        json.dump(data, file, ensure_ascii=False, indent=4)

# Ваши Client ID, Client Secret и OAuth-токен
client_id = "123"
client_secret = "123"
token = "123"

# Получаем информацию о фотослайсе
result = get_photoslice_info(token, client_id, client_secret)

if result:
    print(json.dumps(result, indent=4, ensure_ascii=False))
    save_to_json(result, 'photoslice_info.json')  # Сохраняем в файл

    # Получаем детальную информацию о фотослайсе и ссылки для скачивания
    photoslice_details, download_links = get_photoslice_details_and_download_links(token, result['href'])
    if photoslice_details and download_links:
        print("Детали фотослайса и ссылки для скачивания:")
        print(json.dumps(photoslice_details, indent=4, ensure_ascii=False))
        save_to_json(photoslice_details, 'photoslice_details.json')  # Сохраняем детали в файл
        save_to_json(download_links, 'download_links.json')  # Сохраняем ссылки для скачивания в отдельный файл
`

**Comment by LordSkare** [comment]
В ответе передаются некоторые уникальные параметры, вроде item_id изображения\видео, но я не знаю как их использовать...

**Comment by yeralexey** [comment]
> Нашёл метод получения этих файлов, правда он пока ещё закрыт - я получаю 403 код 
> 
> https://cloud-api.yandex.net/v1/disk/photounlim/resources/last-modified
> https://cloud-api.yandex.net/v1/disk/photounlim/resources/download
> 
> На самом деле довольно много неофициальных способов получения различных данных удалось обнаружить в ходе своих изысканий, в частности связанных с лентой, альбомами, историей изменений и другими, некоторые из них работают. Файлы которые я обнаружил датируются началом 2022 года. К сожалению, Яндекс не торопится обновлять своё API 
> 
> 
> -----------
> 
> I found a method for obtaining these files, although it is still closed - I get a 403 code
> 
> https://cloud-api.yandex.net/v1/disk/photounlim/resources/last-modified
> https://cloud-api.yandex.net/v1/disk/photounlim/resources/download
> 
> In fact, we were able to discover quite a few unofficial methods for obtaining various data during our research, in particular related to the feed, albums, change history and others, some of them work. The files I discovered date back to early 2022. Unfortunately, Yandex is in no hurry to update its API
> 

1. Can it be because you dont have yandex360 subscribe?

2. Can u provide code sample to try, thanks!

**Comment by ivknv** [comment]
It's been quite a while, Yandex still haven't updated the API, so I'm closing the issue for now.

**Comment by ayazzali** [comment]
> Нашёл метод получения этих файлов, правда он пока ещё закрыт - я получаю 403 код
> 
> https://cloud-api.yandex.net/v1/disk/photounlim/resources/last-modified https://cloud-api.yandex.net/v1/disk/photounlim/resources/download
> 
> На самом деле довольно много неофициальных способов получения различных данных удалось обнаружить в ходе своих изысканий, в частности связанных с лентой, альбомами, историей изменений и другими, некоторые из них работают. Файлы которые я обнаружил датируются началом 2022 года. К сожалению, Яндекс не торопится обновлять своё API
> 
> I found a method for obtaining these files, although it is still closed - I get a 403 code
> 
> https://cloud-api.yandex.net/v1/disk/photounlim/resources/last-modified https://cloud-api.yandex.net/v1/disk/photounlim/resources/download
> 
> In fact, we were able to discover quite a few unofficial methods for obtaining various data during our research, in particular related to the feed, albums, change history and others, some of them work. The files I discovered date back to early 2022. Unfortunately, Yandex is in no hurry to update its API

Can u share some urls or notes. I want to do some features at least for my self. i really need tags for y.disk. Ideally at unlimited storage
