### ISSUE TITLE
[Feature Request] link lifetime

### ISSUE THREAD

**Issue by Nikita-Dudorov** [ivknv/yadisk#41]
Is there a friendly way to set lifetime of the link returned by the function "get_download_link()" (https://yadisk.readthedocs.io/ru/latest/_modules/yadisk/client.html#Client.get_download_link)? 
The default lifetime seems to be 5 minutes, and I didn't find a way to change it.

**Comment by ivknv** [comment]
Yandex.Disk's API doesn't expose any way to control link lifespans, so there's no way of doing that.
I guess one is expected to just use the link as soon as possible or get a new one and retry in case it turns out to be expired.

**Comment by Nikita-Dudorov** [comment]
Thanks for reply!
