### ISSUE TITLE
[Question] yadisk.exceptions.UnauthorizedError: Не авторизован. (Unauthorized / UnauthorizedError)

### ISSUE THREAD

**Issue by rvrybak** [ivknv/yadisk#42]
**yadisk.exceptions.UnauthorizedError: Не авторизован. (Unauthorized / UnauthorizedError)**
Использую версию yadisk 1.3.3 в телеграм боте, написанном год назад.
Просрочил истечение срока токена.
Получил новый токен, запустил -> возникает исключение -" yadisk.exceptions.UnauthorizedError: Не авторизован. (Unauthorized / UnauthorizedError)"
исключение происходит на строке   -  if not disk.exists(temp_dir):
в блоке проверки и создания директории
    if not disk.exists(temp_dir):
        disk.mkdir(temp_dir)
        
при этом проверки print(y.check_token()), print(y.get_disk_info()), print(list(y.listdir("/абра))) - выполняются успешно

В настоящий момент в приложении на oauth.yandex.ru вижу следующую надпись с зеленой галочкой:
Приложение подключено
Всё работает и вы получаете авторизации

Все запрашиваемые права - на месте:
Яндекс.Диск WebDAV API
•  Доступ к Яндекс.Диску для приложений
Яндекс.Диск REST API
•  Доступ к папке приложения на Диске
•  Чтение всего Диска
•  Запись в любом месте на Диске
•  Доступ к информации о Диске

Буду благодарен если подскажете - где я затупил))

**Comment by ivknv** [comment]
> исключение происходит на строке - if not disk.exists(temp_dir):

> при этом проверки print(y.check_token()), print(y.get_disk_info()), print(list(y.listdir("/абра))) - выполняются успешно

Выглядит, как будто на момент проверки с помощью метода `exists()` у вас не задан новый токен, других причин для такой ошибки особо нет.

**Comment by rvrybak** [comment]
> > исключение происходит на строке - if not disk.exists(temp_dir):
> 
> > при этом проверки print(y.check_token()), print(y.get_disk_info()), print(list(y.listdir("/абра))) - выполняются успешно
> 
> Выглядит как будто на момент проверки с помощью метода `exists()` у вас не задан новый токен, других причин для такой ошибки особо нет.

Проблема решена. Я затупил))
Начавшему изучать программирование в 45 лет я думаю простительно))
Спасибо, именно Ваш комментарий натолкнул меня на идею в поиске проблемы
Из около 3000 строк кода примерно 2900 строк так называемого "г-но-кода", ->изучал питон сразу на реальной задаче-проекте)) -> без этой мотивации у меня не хватило бы психики.))
Действительно, - токен присутствует в нескольких файлах. В основном файле заменил на новый токен, а в файле из которого отрабатывала функция со строкой в которой ошибка не заменил.
Спасибо за хорошую подсказку и за качественную библиотеку)

**Comment by ivknv** [comment]
> токен присутствует в нескольких файлах

Вообще, старайтесь не хардкодить токены прямо в файлах с исходниками, вместо этого лучше использовать переменные окружения.

> Спасибо за хорошую подсказку и за качественную библиотеку

Рад, что библиотека вам пригодилась.
