### ISSUE TITLE
[Bug] Проблема при сборке .exe файла

### ISSUE THREAD

**Issue by funnyruler** [ivknv/yadisk#44]
При сборке в .exe с помощью pyinstaller и запуске .exe происходит ошибка:
```
Traceback (most recent call last):
  File "yadisk\client.py", line 227, in __init__
  File "yadisk\import_session.py", line 47, in import_session
ModuleNotFoundError: No module named 'yadisk.sessions'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 13, in <module>
  File "yadisk_api.py", line 33, in start_app
  File "yadisk_api.py", line 16, in get_app_token
  File "yadisk\client.py", line 229, in __init__
RuntimeError: requests is not installed. Either install requests or provide a custom session
[15512] Failed to execute script 'main' due to unhandled exception!
```
Пробовал с опцией `--onefile` и без, результат одинаков.

**Как воспроизвести**
Собираем проект в .exe с помощью `pyinstaller --onefile main.py`, запускаем `main.exe`, ловим ошибку.

**Информация о системе:**
 - ОС: Windows 10 x64
 - Версия библиотеки `yadisk`: 2.1.0
 - Версия Python: 3.11

Собирать в .exe зло, конечно, но возникла нужда)

**Comment by ivknv** [comment]
См. issue #43:
> yadisk динамически подгружает модуль `yadisk.sessions.requests_session` (по умолчанию используется requests), PyInstaller этого не видит и не включает в сборку.
> Тут есть 2 варианта решения:
>  1. добавить опцию `--hidden-import=yadisk.sessions.requests_session` при сборке exe'шника
>  2. явно импортировать класс `RequestsSession` и передать в конструкторе `yadisk.Client` `session=RequestsSession()`

**Comment by funnyruler** [comment]
Спасибо за оперативный ответ! С `hidden-import` все работает!
