### ISSUE TITLE
Ошибка import yadisk

### ISSUE THREAD

**Issue by Vasiliy1992** [ivknv/yadisk#47]
Здравствуйте.

При импорте модуля получаю следующее:

> Traceback (most recent call last):
>   File "/home/pi/MyScripts/UploadCSV/RMS_up_YD.py", line 5, in <module>
>     import yadisk
>   File "build/bdist.linux-armv7l/egg/yadisk/__init__.py", line 3, in <module>
>   File "build/bdist.linux-armv7l/egg/yadisk/api/__init__.py", line 4, in <module>
>   File "/home/pi/vRMS/local/lib/python2.7/site-packages/yadisk-2.1.0-py2.7.egg/yadisk/api/api_request.py", line 46
>     url: str = ""
>        ^
> SyntaxError: invalid syntax

Запускаю на оборудовании:

**Raspberry Pi3 B+
Raspbian GNU/Linux 8.0 (jessie)**

**Comment by ivknv** [comment]
Минимальная поддерживаемая версия Python &#8212; 3.8, поэтому такая ошибка.
