### ISSUE TITLE
Download files by public link

### ISSUE THREAD

**Issue by valericus** [ivknv/yadisk#5]
Приветствую.

Отличная либа и красивый код, всё классно разложено по полочкам :-)

Судя по всему, либу будет несложно пропатчить для работы с публичными ссылками на файл (вроде https://yadi.sk/i/LNjClSXFppELzQ): достаточно в метод `yadisk.yadisk.YaDisk#download` (или чуть глубже) захардкодить регулярку, которая будет узнавать такие ссылки, и использовать немного другой URL для запроса `LinkObject`. Или вынести в отдельный метод `download_public`.

В общем, если это интересно, могу сделать PR на досуге.

**Comment by ivknv** [comment]
[`download_public()`](https://yadisk.readthedocs.io/en/latest/docs.html#yadisk.YaDisk.download_public) уже такое поддерживает :)

Такое вполне работает:

```python
y.download_public("https://yadi.sk/i/LNjClSXFppELzQ", "/destination/file")
```

Или вы имеете ввиду ещё некоторые другие методы?

**Comment by valericus** [comment]
Да, действительно. В примере не увидел этого, а вглубь документации посмотреть не подумал :see_no_evil: Спасибо!
