### ISSUE TITLE
[Question] Можно ли качать preview изображений/видео?

### ISSUE THREAD

**Issue by pryadchenko** [ivknv/yadisk#52]
**Краткое описание вашего вопроса**
Можно ли качать preview изображений/видео?

Подробное содержание вопроса.

В API v1/disk/resources, среди прочего, может возвращать пачку preview разного размера. Их можно как-то обрабатывать? В документации не нашел ничего

**Comment by ivknv** [comment]
> Можно ли качать preview изображений/видео?

Можно. Ссылка на превью доступна через атрибут `preview` ресурса:
```python
import yadisk

with yadisk.Client(token="...") as client:
    # Получаем ссылку на превью для my-file.jpg.
    # В ссылке присутствует GET-параметр size, он определяет размер превью.
    # Значение этого параметра можно заменить на другое (XXXS, XXS, XS, S, M, L, XL, XXL, XXXL).
    preview_url = client.get_meta("/my-file.jpg", fields=["preview"]).preview

    # В некоторых случаях превью может отсутствовать (например, для папок)
    if preview_url is None:
        raise ValueError("Отсутствует превью")

    # Теперь скачиваем превью по полученной ссылке в файл my-file-preview.jpg.
    # Можно также скачать файл с помощью любой другой HTTP библиотеки обычным GET запросом.
    client.download_by_link(
        preview_url,
        "my-file-preview.jpg",
        # Для скачивания превью нужно дополнительно указать токен в заголовках
        headers={"Authorization": f"OAuth {client.token}"}  
    )
```

> В API v1/disk/resources, среди прочего, может возвращать пачку preview разного размера. Их можно как-то обрабатывать?

На [полигоне](https://yandex.ru/dev/disk/poligon) добавили поле `sizes` со ссылками на все размеры превью, но в текущей версии библиотеки он недоступен, добавлю в следующей. Пока что единственный способ выбрать размер превью &#8212; это изменять параметр `size` в полученной ссылке.

**Comment by pryadchenko** [comment]
Да вот получаю 403 по этой ссылке get запросом (при этом сам файл по
download линке качается). Только в браузере, где авторизован в Яндексе,
могу открыть preview без ошибки.

вт, 27 авг. 2024 г., 19:24 Ivan Konovalov ***@***.***>:

**Comment by ivknv** [comment]
> получаю 403

Нужно в заголовках запроса ещё указать токен (как в примере выше), тогда файл скачается.

**Comment by pryadchenko** [comment]
Признаюсь, попробовал через curl, и токен указывал. Через ваш пакет не
пробовал - как раз на него набрел в поисках решения. Попробую

вт, 27 авг. 2024 г., 19:46 Ivan Konovalov ***@***.***>:

**Comment by pryadchenko** [comment]
Работает, спасибо!
