### ISSUE TITLE
Upload file by link

### ISSUE THREAD

**Issue by NotStatilko** [ivknv/yadisk#6]
Привет! Можно ли как-то с помощью этой библиотеки загрузить файл на диск через прямую ссылку из интернета? Видел такое на https://tech.yandex.ru/disk/api/reference/upload-ext-docpage/

Спасибо!

**Comment by ivknv** [comment]
Для этого есть метод [upload_url()](https://yadisk.readthedocs.io/en/latest/docs.html#yadisk.YaDisk.upload_url).

**Comment by NotStatilko** [comment]
Да, так долбиться в глаза ещё нужно уметь

Спасибо x2 !
