### ISSUE TITLE
Получение содержимого подпапок публичного ресурса

### ISSUE THREAD

**Issue by Maxtodont** [ivknv/yadisk#7]
При вызове метода `y.public_listdir(public_key, path='/вложенная папка')` с параметром 'path' возникает следующая ошибка:
`TypeError: _listdir() got multiple values for argument 'path'` 
Параметр path, согласно документации, нужен для обращения к вложенным ресурсам (подпапкам).
Изменив аргумент path и все его вхождения в функции `def _listdir(get_meta_function, session, path, **kwargs)` (файл functions/resources.py LINE 283) на `public_key` ошибка была устранена.

**Comment by ivknv** [comment]
Спасибо за информацию! Исправил в [последнем](https://github.com/ivknv/yadisk/commit/a41c42644b7e35c0852d563ef44c44538eef0fe5) коммите.
