### ISSUE TITLE
Предложение - поддержка асинхронных запросов

### ISSUE THREAD

**Issue by Andrej730** [ivknv/yadisk#8]
Хотелось бы иметь поддержку асинхронно скачивать/загружать файлы с помощью библиотеки. Это планируется добавить в будущем или считается нецелесообразным (почему?)?

**Comment by ivknv** [comment]
Добавлять поддержку асинхронных запросов я не планирую.
Я не думаю что это относится к данной библиотеке. Если вам это нужно, вы это и так можете сделать достаточно просто, например с помощью [concurrent.futures](https://docs.python.org/3/library/concurrent.futures.htmll) или со своей реализацией пулов.
Кроме того, не существует одного оптимального способа реализации асинхронных запросов, который бы подходил в большинстве случаев.

В общем, мне кажется, что (простое) асинхронное выполнение запросов &#8212; это и так достаточно тривиальная вещь (в питоне), а в более сложных случаях всё равно придётся писать собственную реализацию, поэтому смысла добавлять это в библиотеку я особо не вижу.

**Comment by Andrej730** [comment]
Я скорее имел ввиду не concurrent.futures или что-то подобное, а добавление возможности запускать функции библиотеки вместе с await, использование вместо requests aiohttp и т.д. Или это тоже не по адресу?

**Comment by ivknv** [comment]
Хмм... В принципе я мог бы реализовать это в будущем. Единственное, что, насколько я понимаю, придётся продублировать весь API, чтобы были и асинхронные запросы, и синхронные.
С текущей архитектурой библиотеки это проблематично (в особенности использование чего-то кроме requests), но я собираюсь этим летом (надеюсь, что это с середины июня) как раз решить некоторые архитектурные проблемы библиотеки (самая большая проблема &#8212; это зависимость от requests), вместе с этим и попробую добавить асинхронность.
Ну а пока что я занят работой над другими вещами, свободного времени не очень много.

Спасибо за предложение.

**Comment by Andrej730** [comment]
Прекрасно, в будущем надеюсь перевести несколько своих приложений на ЯДиск, если будет такая возможность.
Немного не по теме, но захотел узнать - а в чём проблема зависимости от requests для библиотеки? Или вы имели ввиду это проблема в контексте перехода на асинхронные запросы?

**Comment by ivknv** [comment]
У requests есть некоторые ограничения, например нет возможности отслеживать прогресс загрузки файла на сервер (например, узнать сколько байт залилось на данный момент), ограничить скорость и нет прямого способа прервать запрос. Дело даже не в асинхронности. Эти проблемы частично решаются через всякие трюки, я сейчас так и делаю, но это только частичные решения, у них есть свои проблемы.

Я не то чтобы хочу конкретно избавиться от requests, а добавить возможность использовать что-нибудь другое при необходимости, чтобы не было вышеописанных проблем.

**Comment by ivknv** [comment]
Сделал отдельную библиотеку: [yadisk-async](https://github.com/ivknv/yadisk-async).
API практически идентичный, вместо requests использует aiohttp.

Использовать пока с осторожностью, всё-таки ещё мало времени пока прошло.
