### ISSUE TITLE
Download link shortener function

### ISSUE THREAD

**Issue by sergey-sc** [ivknv/yadisk#9]
Hello, thanks for plugin. Could you include link shortener into download_link functions. It's will be very useful opportunity, because now the output links are very big and inconvenient to put them into mail with plain text.
Thank you in advance

**Comment by ivknv** [comment]
I'm not sure, but I think short URLs are only available for public files (see [publish()](https://yadisk.readthedocs.io/en/latest/docs.html#yadisk.YaDisk.publish)).
For public files you can just use the `public_url` property (see [ResourceObject.public_url](https://yadisk.readthedocs.io/en/latest/docs.html#yadisk.objects.resources.ResourceObject)).

For non-public files it seems you can't get a short link.

**Comment by sergey-sc** [comment]
> I'm not sure, but I think short URLs are only available for public files (see [publish()](https://yadisk.readthedocs.io/en/latest/docs.html#yadisk.YaDisk.publish)).
> For public files you can just use the `public_url` property (see [ResourceObject.public_url](https://yadisk.readthedocs.io/en/latest/docs.html#yadisk.objects.resources.ResourceObject)).
> 
> For non-public files it seems you can't get a short link.

Guess, you are right.
Clear. Thanks for reply!
